### ISSUE TITLE
Stopped working with new versions of CDK 2.2x

### ISSUE THREAD

**Issue by jhallerdk** [wheatstalk/fargate-spot-fallback#166]
When deploying with newer versions of CDK, if fails to deploy services with the fallback policy.

The error: 
"Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: Lambda, Status Code: 400, Request ID: XXX)" (RequestToken: XXX, HandlerErrorCode: InvalidRequest)".

This is when it tries to deploy the Service Logretention policy.

We have tried to deploy without the fallback policy, and that works. And also CDK 2.15 works with fallback policy. However newer versions of CDK no longer works, if the fallback policy is defined.

**Comment by misterjoshua** [comment]
I can't seem to reproduce this issue with AWS CDK 2.21.1. But, I did just release an update this morning, so I'm not sure if I've inadvertently fixed the issue. If with v0.1.47 you still have the issue, could you please provide an [SSCCE](http://sscce.org/) I can use to reproduce the problem locally?
